### PR TITLE
Linkify URLs in plain text output

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/nteract/nteract/issues/993

### CODE REVIEW

**Comment by rgbkrk** [comment]
All the tests are failing, how's master look right now?

**Comment by gnestor** [comment]
No it master is passing so it looks like my commit is breaking carriage return handling and the `el.html()` assertions are failing.

**Comment by gnestor** [comment]
Ok, tests are passing locally 👌

**Comment by rgbkrk** [comment]
Nice! Want to ship this too? I can give you rights on npm.

**Comment by rgbkrk** [comment]
Might as well make it a major bump (and start us off at 1.0.0).

**Comment by rgbkrk** [comment]
Added you on npm.

**Pull request merged**
