### PR TITLE
Add optional className prop

### PR DESCRIPTION
**Pull request by lgeiger**
Required for https://github.com/nteract/hydrogen/pull/772

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'll make a minor release with this now.

**Comment by lgeiger** [comment]
Thanks! Though it looks like it isn't published on npm: https://www.npmjs.com/package/ansi-to-react

**Comment by rgbkrk** [comment]
Ok, it should _actually_ be published now. Apparently I only did the first few steps. 
¯\\\_(ツ)\_/¯

**Comment by lgeiger** [comment]
Thanks :+1:

**Pull request merged**
